# Generated by Django 5.1.7 on 2025-05-14 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_conversationhistory_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversationhistory",
            old_name="history",
            new_name="flow",
        ),
    ]
