# Generated by Django 5.1.7 on 2025-05-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_history_conversationhistory_flow"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationhistory",
            name="history",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
