# Generated by Django 5.1.7 on 2025-05-14 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_conversationhistory_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversationhistory",
            name="flow",
        ),
    ]
