# Generated by Django 5.1.7 on 2025-05-14 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_conversationhistory_flow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversationhistory",
            old_name="history",
            new_name="flow",
        ),
    ]
