# Generated by Django 5.1.7 on 2025-05-14 04:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_conversationhistory_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationFlow",
            fields=[
                (
                    "conversation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("flow", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name_plural": "Conversation Histories",
            },
        ),
        migrations.DeleteModel(
            name="ConversationHistory",
        ),
    ]
